# Generated by Django 5.1.4 on 2025-02-18 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_serializer', '0002_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employeee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn_serializer.department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_worked', models.IntegerField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn_serializer.employeee')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn_serializer.project')),
            ],
        ),
    ]
