# Generated by Django 5.1.4 on 2025-02-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn_serializer', '0003_department_project_employeee_employee_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_project',
            old_name='project_id',
            new_name='project_name',
        ),
    ]
